---
title: "gtsummary"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gtsummary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(gtsummary)

tbl1 <- 
  trial %>%
    tbl_summary(
        by = response, 
        include = c(age, grade, trt), 
        type = list(
          all_dichotomous() ~ "categorical",
          age ~ "continuous"),
        missing = "no",
        percent = "row"
    ) %>%
    add_p()

tbl2 <- 
  trial %>%
  filter(is.na(response)) |> 
    tbl_summary(
        # by = response, 
        include = c(age, grade, trt), 
        type = list(
          all_dichotomous() ~ "categorical",
          age ~ "continuous"),
        missing = "no",
        percent = "column"
    )

list(tbl1, tbl2) |> 
  tbl_merge(tab_spanner = c("**Tumor Response**", "**Missing**"))
```


```{r}
my_ttest <- function(data, variable, by, ...) {
  t.test(data[[variable]] ~ as.factor(data[[by]]))$p.value
}

trial |>
  tbl_summary(
    by = response,
    include = c(trt, age, marker),
    missing = "no"
  ) |>
  add_stat(fns = everything() ~ my_ttest) |>
  modify_header(add_stat_1 = "**p-value**", all_stat_cols() ~ "**{level}**")

```

