---
title: "logistic"
format: html
editor: visual
---

```{r, engine = 'tikz'}
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric}
\usetikzlibrary{decorations.pathreplacing}
\usetikzlibrary{arrows}
\begin{tikzpicture}[->,>=stealth',auto,decoration={brace,raise=2pt}]
  \node [rectangle] (pi) {$\pi$};
  \node (omega) [right of=pi] {$\omega$};
  \node (eta) [right of=omega] {Test $\eta$};
  \path[every node/.style={font=\sffamily\small}]
  (pi) edge [bend right] (omega)
  (omega) edge [bend left] (pi);
  \draw [->] (omega) to [out=150,in=30] (pi);
 

\end{tikzpicture}
```

```{r, engine = 'tikz'}
\usetikzlibrary{positioning}
\usetikzlibrary{shapes.geometric, arrows}
\usetikzlibrary{decorations.pathreplacing}
\tikzstyle{arrow} = [thick,->,>=stealth]
\begin{tikzpicture}[decoration={brace,raise=2pt}]
\node [rectangle] (pop) {Population$\beta = \int_{t=0}^\infty x^2dx$};
  \node [ellipse] (y1) [below of=pop] {$y_1$};
  \node [ellipse] (y2) [left of=y1] {$y_2$};
  \draw  [arrow] (pop.east) to (y1.east);
  \draw[decorate] (y1.south east) -- (y2.south west) node[midway,below=3pt](ABC){ABCDEFG};

\end{tikzpicture}
```

