---
title: "subfigures"
format: 
  docx:
    toc: false
    echo: false
    # fig-format: svg
    toc-depth: 4
    # cap-location: top
    # fig-cap-location: top # causes extra newlines above subcaps in docx
    tbl-cap-location: top
    number-sections: true
    number-depth: 3
    link-citations: true
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    embed-resources: true
    appendix-style: plain
    mainfont: serif
crossref:
  appendix-title: "Supplemental Materials" # doesn't seem to work
  custom:
    - kind: float
      key: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
    - kind: float
      key: supptbl
      reference-prefix: Table S
      space-before-numbering: false

---

```{r}
x <- "A test label"
```

::::: {#suppfig-test layout="[[ 50, 50 ]]"}

```{r}
#| label: suppfig-test-1
#| fig-cap: !expr x
plot(cars)
```


```{r}
#| label: suppfig-test-2
#| fig-cap: !expr x
plot(pressure)
```

`{r} x`

:::::

See @fig-test-2 and @suppfig-test-2

{{< pagebreak >}}

```{r}
temp = "Speed and Stopping Distances of Cars"
```

```{r}
#| label: "fig-first-only"
#| fig-cap: "Estimated event sequence models, stratified by sex, first visits only"
#| layout-ncol: 2
#| fig-subcap:
#|   - "Males"
#|   - "Females"

plot(cars)
plot(pressure)
```

::: {#fig-first-only layout="[[ 50, 50 ]]" layout-ncol="2"}

```{r}
#| fig-subcap:
#|   - "Males1"
#|   - "Females1"
#| fig-width: 2
plot(cars)
plot(pressure)
```

figure 50/50

:::


::: {#suppfig-second layout="[[ 50, 50 ]]"}

```{r}
#| label: suppfig-second-1
#| fig-cap: "males1"

plot(cars)
```

```{r}
#| label: suppfig-second-2
#| fig-cap: "females1"
plot(pressure)
```

second figure

:::

See @fig-subfigs-1 and @fig-subfigs-2:

::: {#fig-subfigs layout="[[ 50, 50 ]]"}

:::: {#fig-subfigs-1}

```{r}
#| fig-width: 2
#| fig-height: 3
plot(cars)
```

Cars

::::

:::: {#fig-subfigs-2}

```{r}
#| fig-width: 2
#| fig-height: 3
plot(pressure)
```

Pressure

::::
Charts

:::